# Generated by Django 3.1.6 on 2021-04-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210422_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField(default='')),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='lugar',
        ),
        migrations.RemoveField(
            model_name='article',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='article',
            name='superficie',
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='price',
            field=models.IntegerField(default='1'),
        ),
    ]
