# Generated by Django 3.1.6 on 2021-05-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_tabla1_lugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabla1',
            name='lugar',
            field=models.CharField(choices=[('0', 'Cantabria'), ('1', 'Asturias')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tabla1',
            name='mes',
            field=models.CharField(choices=[('0', 'enero'), ('1', 'febrero'), ('2', 'marzo')], default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='tabla1',
            name='superficie',
            field=models.CharField(choices=[('0', 'asfalto'), ('1', 'trail')], default='none', max_length=100),
        ),
    ]
