# Generated by Django 3.1.6 on 2021-05-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210522_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabla1',
            name='fecha',
            field=models.DateField(default='2021-01-01'),
        ),
    ]
