# Generated by Django 3.1.6 on 2021-05-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210522_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='distancia',
            field=models.CharField(choices=[('1milla', '1milla'), ('5km', '5km'), ('10km', '10km'), ('15km', '15km'), ('21.096km', '21.096km'), ('42.192km', '42.192km')], default='none', max_length=100),
        ),
    ]
