# Generated by Django 3.1.6 on 2021-05-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_calendario_distancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='web',
            field=models.EmailField(default='none', max_length=100),
        ),
    ]
