# Generated by Django 3.1.6 on 2021-05-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_calendario_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='web',
            field=models.URLField(default='none', max_length=100),
        ),
    ]
