# Generated by Django 3.1.6 on 2021-07-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210710_1734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tabla1',
        ),
        migrations.AddField(
            model_name='calendario',
            name='distancia_real',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
