# Generated by Django 3.1.6 on 2021-07-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20210717_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='superficie',
            field=models.CharField(choices=[('Asfalto', 'Asfalto'), ('Trail', 'Trail')], default='none', max_length=100),
        ),
    ]
